;;设置国内镜像站
(setq package-archives '(("gnu" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
			 ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
			 ("nognu" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/nognu/")
			 ))
(setq package-check-signature nil)
(require 'package)
(unless (bound-and-true-p package--initialized)
  (package-initialize))
(unless package-archive-contents
  (package-refresh-contents))
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(setq use-package-always-ensure t)
(setq use-package-always-defer t)
(setq use-package-always-demand nil)
(setq use-package-expand-minimally t)
(setq use-package-verbose t)
(require 'use-package)

(use-package restart-emacs)
(use-package exec-path-from-shell)
(use-package timu-rouge-theme)
(use-package ace-window)
(use-package amx)
(use-package anzu)

(provide 'packages-install)
